### ISSUE TITLE
BUG: Plugin requires Memberlite theme but doesn't check if active

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/memberlite-shortcodes#15]
Memberlite shortcodes require the Memberlite theme but don't check whether the theme it requires and depends on is installed and active.

**Comment by ipokkel** [comment]
Fix for this issue here: https://github.com/strangerstudios/memberlite-shortcodes/pull/17

**Comment by kimcoleman** [comment]
Are you getting a fatal error if you using the shortcodes plugin without Memberlite? While using this with Memberlite is the ideal situation, they don't require each other. Some styles may be missing or less exact of a match to the demos, but it shouldn't break a site to use this without Memberlite as your theme.

If you point me to where it is throwing a fatal error or if this is a design that needs to be matched in this plugin I can adjust it.
